version: '3.8'

services:
  cyprus_news:
    build: .
    container_name: cyprus_news
    volumes:
      - /volume1/dockerdata/cyprus_news/data:/app/data
      - /volume1/dockerdata/cyprus_news/summaries:/app/summaries
      - /volume1/dockerdata/secrets/cyprus_news:/app/secrets
    environment:
      OPENAI_API_KEY: foo
      PUBLICATION_URL: https://cyprusnews.substack.com
      EMAIL: alex.toumazis@gmail.com
      PASSWORD: bar
    working_dir: /app
    restart: unless-stopped
    entrypoint: ["cron", "-f"]
